output_subdir: null  
run:  
  dir: .
sweep:
  dir: ./outputs/${now:%Y%m%d_%H%M%S}
  subdir: ${hydra.job.num}_${hydra.job.id}
job: 
  chdir: true # automatically change to the working directory
verbose: [__main__] 

  