defaults:
  - hydra: default  
  - wandb_cfg@wandb: default
  - _self_

experiment: 
  model: PABBO
  mode: eval
  expid: ${experiment.model}_${data.name}_${now:%Y%m%d_%H%M%S}
  device: cuda
  resume: false
  wandb: true

wandb: 
  name: ${experiment.expid}
  group: ${experiment.model}
  job_type: debug
  tags: ['${experiment.model}', evaluation, '${data.name}']
  
eval: 
  eval_num_query_points: 1024
  p_noise: 0.
  eval_max_T: 30
  argmax: false